name: GHCR Workflow

on:
  - push

env:
    CONTAINER_REGISTRY: ghcr.io
    IMAGE_NAME: test-app2
    TAG: ${{ github.event.pull_request.number }}
    GitHub_User: getdzidon

permissions:
    id-token: write
    contents: write
    packages: write

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

# Pushing to GitHub Container Registry (GHCR)
    - name: GHCR Login
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}  
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Publish code to GHCR
      run: |
        docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.GitHub_User }}/${{ env.IMAGE_NAME }}:${{ github.event.pull_request.number }} . 
        docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.GitHub_User }}/${{ env.IMAGE_NAME }}:${{ github.event.pull_request.number }} 