name: Docker Workflow

on:
  - push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: test-app

permissions:
    id-token: write
    contents: write
    packages: write

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

# Pushing to GitHub Container Registry (GHCR)
    - name: GHCR Login
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Publish code to GHCR
      run: |
        docker build -t ghcr.io/jomacs-it/test-app:latest . 
        docker push ghcr.io/jomacs-it/test-app:latest 