name: npm Audit Security Check

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: |
          npm audit --audit-level=high --json > audit-result.json
          cat audit-result.json
          high_vulns=$(jq '[.advisories[] | select(.severity=="high")] | length' audit-result.json)
          if [ $high_vulns -gt 0 ]; then
            echo "Found high vulnerabilities in the dependencies!"
            exit 1
          fi

      - name: Fail on high vulnerabilities
        if: failure()
        run: echo "High vulnerabilities detected! Failing the workflow."
