name: Snyk Security Scan

on:
  push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate package.json file
        run: npm init -y

      - name: Install dependencies
        run: npm install

      - name: Run Snyk Security Scan (Test)
        run: snyk test --all-projects --json  # Run Snyk test to find vulnerabilities

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Run Snyk Security Scan (Test and Monitor)
        uses: snyk/actions/node@v4  # Use the Snyk Action for both test and monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}